CREATE DATABASE NaN
GO

USE NaN
GO

CREATE TABLE Aplicaciones(
	ID BIGINT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(40) NOT NULL,
)
GO

CREATE TABLE Usuarios(
	EMail VARCHAR(120) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(150) NOT NULL,
	FechaNac DATE NULL,
)

CREATE TABLE Usuarios_x_Aplicacion(
	IDApp BIGINT NOT NULL FOREIGN KEY REFERENCES Aplicaciones(ID),
	EMail VARCHAR(120) NOT NULL FOREIGN KEY REFERENCES Usuarios(Email),
	HorasDeUso BIGINT NULL,
)
GO