--CREATE DATABASE RELACION1A1
--USE RELACION1A1

CREATE TABLE AUTOS(
	PATENTE VARCHAR(9) NOT NULL PRIMARY KEY,
	MARCA VARCHAR(25) NOT NULL,
	MODELO VARCHAR(25) NOT NULL,
	FECHADEFABRICACION DATE NOT NULL CHECK (FECHADEFABRICACION < GETDATE())
)
CREATE TABLE AUTOPARTES(
	PATENTE VARCHAR(9) NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES AUTOS(PATENTE),
	NUMEROCHASIS VARCHAR(25) NOT NULL UNIQUE,
	NUMEROMOTOR VARCHAR(25)  NOT NULL UNIQUE,
)
